"""Shared retrieval ranking, filtering, deduplication, and rendering policy."""

from __future__ import annotations
from memory.retrieval_metadata import (
    attach_cargo_crate_meta,
    cap_per_dir,
    cap_per_file,
    cargo_manifest_dir,
    coerce_meta,
    filter_by_cargo_crate,
    format_meta,
    match_cargo_crate,
    meta_score,
    passes_filters,
    path_allowed,
    render_results,
)
from memory import retrieval_duplicates as _retrieval_duplicates
from memory.retrieval_duplicates import (
    analyze_near_duplicate_results,
    candidate_relevance_score,
    rerank_diverse_results,
    trace_diverse_results,
)
from memory.retrieval_contracts import (
    compact_duplicate_analysis,
    compact_implementation_ranking_trace,
    compact_rerank_contract,
    result_label,
    summarize_trace_for_debug,
)
from memory.retrieval_enrichment import (
    build_implementation_ranking_trace,
    dedupe_files,
    enrich_implementation_result,
)
from memory.retrieval_intent import (
    implementation_expected_runtime_entrypoint_paths,
    implementation_inferred_filename_hints,
    implementation_intent_policy,
    implementation_noise_exclude_patterns,
    implementation_provider_query_tokens,
    implementation_query_accepts_generated_surfaces,
    implementation_query_class,
    implementation_query_exact_identifiers,
    implementation_query_intent,
    implementation_query_prefers_command_definition,
    implementation_query_prefers_dispatchers,
    implementation_query_prefers_provider_wiring,
    implementation_query_prefers_request_routing,
    implementation_query_prefers_runtime_main_entrypoint,
    implementation_query_prefers_supporting_context,
    implementation_query_relaxes_dir_cap,
    implementation_support_surface_penalties,
    implementation_usage_surface_bonus,
    query_class_prefers_definitions,
    query_class_prefers_usage,
    usage_query_prefers_example_results,
    usage_query_prefers_test_results,
)
from memory.retrieval_scoring import (
    implementation_api_context_hit,
    implementation_api_entrypoint_hit,
    implementation_basename_token_hit,
    implementation_command_definition_priority,
    implementation_controller_entity_hit,
    implementation_declared_symbol_hit,
    implementation_definition_hit,
    implementation_dispatcher_contract_priority,
    implementation_dispatcher_priority,
    implementation_exact_identifier_hit,
    implementation_exact_member_usage_hit,
    implementation_exact_member_usage_site_hit,
    implementation_exact_signature_symbol_hit,
    implementation_export_hit,
    implementation_facade_surface_hit,
    implementation_path_hint_hit,
    implementation_provider_wiring_penalty,
    implementation_provider_wiring_priority,
    implementation_reexport_surface_hit,
    implementation_request_handler_priority,
    implementation_routing_priority,
    implementation_runtime_main_entrypoint_hit,
    implementation_runtime_main_entrypoint_hit_with_meta,
    implementation_server_infra_penalty,
    implementation_symbol_hit,
    implementation_view_body_priority,
)
from memory.retrieval_semantics import (
    apply_result_surface_flags,
    implementation_chunk_role,
    implementation_declared_symbol_roles,
    implementation_declares_callable,
    implementation_file_roles,
    implementation_has_file_roles,
    implementation_is_profile_candidate,
    implementation_member_usages,
    implementation_node_types,
)
from memory.retrieval_query import (
    implementation_query_definition_subject_identifiers,
    implementation_query_member_exprs,
    implementation_query_path_hints,
    implementation_query_symbols,
)
from memory.retrieval_rank_policy import (
    NODE_TYPE_POLICY_DEFINITION as NODE_TYPE_POLICY_DEFINITION,
    NODE_TYPE_POLICY_EXPLANATION as NODE_TYPE_POLICY_EXPLANATION,
    NODE_TYPE_POLICY_IMPLEMENTATION as NODE_TYPE_POLICY_IMPLEMENTATION,
    NODE_TYPE_POLICY_USAGE as NODE_TYPE_POLICY_USAGE,
    ROLE_POLICY_DEFINITION as ROLE_POLICY_DEFINITION,
    ROLE_POLICY_EXPLANATION as ROLE_POLICY_EXPLANATION,
    ROLE_POLICY_IMPLEMENTATION as ROLE_POLICY_IMPLEMENTATION,
    ROLE_POLICY_USAGE as ROLE_POLICY_USAGE,
    implementation_node_type_policy,
    implementation_node_type_priority,
    implementation_node_type_score,
    implementation_result_role,
    implementation_role_policy,
    implementation_role_priority,
    implementation_role_score,
)
from memory.retrieval_surfaces import (
    implementation_rank_tuple,
    is_doc_like_path as is_doc_like_path,
    is_generated_implementation_surface_path,
    is_low_signal_binding_surface_path as is_low_signal_binding_surface_path,
    is_low_signal_parser_data_path,
    is_low_signal_support_path,
    is_usage_heavy_path,
)
from memory.retrieval_telemetry import (
    append_dispatcher_telemetry_event,
    append_duplicate_telemetry_event,
    append_routing_telemetry_event,
    dispatcher_contract_telemetry,
    dispatcher_telemetry_enabled,
    duplicate_experiment_flags_from_env,
    duplicate_experiment_flags_with_query_class,
    duplicate_telemetry_enabled,
    merge_duplicate_experiments,
    routing_signal_telemetry,
    routing_telemetry_enabled,
)

__all__ = [
    "append_dispatcher_telemetry_event",
    "append_duplicate_telemetry_event",
    "append_routing_telemetry_event",
    "trace_diverse_results",
    "rerank_retrieval_results_contract",
    "rerank_diverse_results",
    "collapse_near_duplicate_results",
    "candidate_relevance_score",
    "analyze_near_duplicate_results",
    "analyze_duplicate_results_contract",
    "apply_result_surface_flags",
    "attach_cargo_crate_meta",
    "build_implementation_ranking_trace",
    "cap_per_dir",
    "cap_per_file",
    "cargo_manifest_dir",
    "coerce_meta",
    "compact_duplicate_analysis",
    "compact_implementation_ranking_trace",
    "compact_rerank_contract",
    "dispatcher_telemetry_enabled",
    "dispatcher_contract_telemetry",
    "duplicate_experiment_flags_from_env",
    "duplicate_experiment_flags_with_query_class",
    "duplicate_telemetry_enabled",
    "dedupe_files",
    "enrich_implementation_result",
    "filter_by_cargo_crate",
    "format_meta",
    "implementation_api_context_hit",
    "implementation_api_entrypoint_hit",
    "implementation_basename_token_hit",
    "implementation_command_definition_priority",
    "implementation_controller_entity_hit",
    "implementation_chunk_role",
    "implementation_declares_callable",
    "implementation_definition_hit",
    "implementation_expected_runtime_entrypoint_paths",
    "implementation_dispatcher_contract_priority",
    "implementation_dispatcher_priority",
    "implementation_exact_identifier_hit",
    "implementation_exact_member_usage_hit",
    "implementation_exact_member_usage_site_hit",
    "implementation_exact_signature_symbol_hit",
    "implementation_export_hit",
    "implementation_facade_surface_hit",
    "implementation_file_roles",
    "implementation_inferred_filename_hints",
    "implementation_intent_policy",
    "implementation_path_hint_hit",
    "implementation_node_type_policy",
    "implementation_node_type_priority",
    "implementation_node_type_score",
    "implementation_node_types",
    "implementation_member_usages",
    "implementation_noise_exclude_patterns",
    "implementation_provider_wiring_penalty",
    "implementation_provider_wiring_priority",
    "implementation_is_profile_candidate",
    "implementation_provider_query_tokens",
    "implementation_query_accepts_generated_surfaces",
    "implementation_query_class",
    "implementation_query_definition_subject_identifiers",
    "implementation_query_exact_identifiers",
    "implementation_query_member_exprs",
    "implementation_query_path_hints",
    "implementation_query_intent",
    "implementation_query_prefers_command_definition",
    "implementation_query_prefers_dispatchers",
    "implementation_query_prefers_provider_wiring",
    "implementation_query_prefers_request_routing",
    "implementation_query_prefers_runtime_main_entrypoint",
    "implementation_query_prefers_supporting_context",
    "implementation_query_relaxes_dir_cap",
    "implementation_query_symbols",
    "implementation_rank_tuple",
    "implementation_reexport_surface_hit",
    "implementation_request_handler_priority",
    "implementation_result_role",
    "implementation_role_policy",
    "implementation_role_priority",
    "implementation_role_score",
    "implementation_routing_priority",
    "implementation_runtime_main_entrypoint_hit",
    "implementation_runtime_main_entrypoint_hit_with_meta",
    "implementation_declared_symbol_roles",
    "implementation_declared_symbol_hit",
    "implementation_has_file_roles",
    "implementation_server_infra_penalty",
    "implementation_support_surface_penalties",
    "implementation_symbol_hit",
    "implementation_usage_surface_bonus",
    "implementation_view_body_priority",
    "is_doc_like_path",
    "is_generated_implementation_surface_path",
    "is_low_signal_binding_surface_path",
    "is_low_signal_parser_data_path",
    "is_low_signal_support_path",
    "is_usage_heavy_path",
    "match_cargo_crate",
    "meta_score",
    "merge_duplicate_experiments",
    "passes_filters",
    "path_allowed",
    "query_class_prefers_definitions",
    "query_class_prefers_usage",
    "result_label",
    "render_results",
    "routing_telemetry_enabled",
    "routing_signal_telemetry",
    "summarize_trace_for_debug",
    "usage_query_prefers_example_results",
    "usage_query_prefers_test_results",
]


_context_payload = _retrieval_duplicates._context_payload


def collapse_near_duplicate_results(results: list[dict], *, query: str = "", mode: str = "code") -> list[dict]:
    return _retrieval_duplicates.collapse_near_duplicate_results(
        results,
        query=query,
        mode=mode,
        rerank_fn=rerank_retrieval_results_contract,
    )


def analyze_duplicate_results_contract(
    results: list[dict],
    *,
    query: str = "",
    mode: str = "code",
) -> dict:
    return _retrieval_duplicates.analyze_duplicate_results_contract(
        results,
        query=query,
        mode=mode,
        analyze_fn=analyze_near_duplicate_results,
    )


def rerank_retrieval_results_contract(
    results: list[dict],
    *,
    query: str = "",
    mode: str = "code",
    experiments: dict | None = None,
    include_debug: bool = False,
) -> dict:
    return _retrieval_duplicates.rerank_retrieval_results_contract(
        results,
        query=query,
        mode=mode,
        experiments=experiments,
        include_debug=include_debug,
        trace_fn=trace_diverse_results,
        analyze_fn=analyze_near_duplicate_results,
    )
